### ISSUE TITLE
Uable to install v.0.18.5 on Windows

### ISSUE THREAD

**Issue by Kornform** [chaiNNer-org/chaiNNer#1735]
Hey, did anybody encounter this issue as well? When trying to install it the first time, Windows had a pop saying something about "not trustworthy". I clicked "trust anyways" and from there on nothing happens after starting the exe file. 

Are there any steps I have to do beforehand etc.? Or is there a way to fix it?

**Comment by joeyballentine** [comment]
When you ran it, did it pop up with a little animation? It should have animated for a bit, then closed. Then you should be able to launch the program like normal

**Comment by AAAlexander** [comment]
same here... no animation, no installation... just a few seconds of loading pointer animation.

**Comment by joeyballentine** [comment]
Make sure when you launch it, you do so from windows explorer and not from your browsers download bar.

Side note, I'll be getting a code signing certificate this weekend, so hopefully this won't be an issue anymore after that

**Comment by theflyingzamboni** [comment]
It may actually be installed. There's been a bug since the CLI was added that causes the program to not open automatically after installation. Check appdata/roaming to see if it's actually there, and launch the exe if it is to see what version you have if you are just updating.

**Comment by Kornform** [comment]
> It may actually be installed. There's been a bug since the CLI was added that causes the program to not open automatically after installation. Check appdata/roaming to see if it's actually there, and launch the exe if it is to see what version you have if you are just updating.

You're right, it was actually installed and I didn't notice it. So for me the problem is solved then :)

**Comment by AAAlexander** [comment]
> It may actually be installed. There's been a bug since the CLI was added that causes the program to not open automatically after installation. Check appdata/roaming to see if it's actually there, and launch the exe if it is to see what version you have if you are just updating.

unfortunately in my case has not been installed

**Comment by AAAlexander** [comment]
Yes, also tried to run as admin. The portable version won't star... ideas?

**Comment by joeyballentine** [comment]
By "it won't start" do you mean absolutely nothing happens? Or does the program start staring up and then closes? Or you get an error?

**Comment by Potato22** [comment]
Hello, this still happening on 0.18.6. 
The installer will do absolutely nothing upon opening even with admin elevation. It will display the loading animation for approx 4 seconds and disappear with no changes on anything at all.

**Comment by joeyballentine** [comment]
@Potato22  yes it is a known issue. it still should have installed. If you search for chaiNNer on your computer it should be there.

**Comment by Potato22** [comment]
verified, chainner is installed and visible on start search.
